name: Restaurant Ionic CI
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test:dev

      - name: Build
        run: yarn build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          fail_ci_if_error: true
          name: codecov-umbrella
          verbose: true
