name: Restaurant Ionic CI
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install --network-concurrency 1

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - uses: artiomtr/jest-coverage-report-action@v2.2.5
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          package-manager: yarn
          threshold: ${{steps.threshold.outputs.prop}}
          skip-step: all
          annotations: failed-tests
